name: "Build and Release"

on: push

env:
  CRYSTAL_VERSION: 1.5.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: shards install

      - name: Run linter
        run: crystal bin/ameba.cr

      - name: Run tests
        run: crystal spec --order random
